name: "Bug Report"
description: "Report a problem that affects reliability or accuracy."
title: "[Bug]: "
labels: ["bug", "reliability"]
body:
  - type: textarea
    attributes:
      label: "Describe the issue"
      description: "Include what you expected vs what happened."
  - type: textarea
    attributes:
      label: "Steps to reproduce"
  - type: input
    attributes:
      label: "Environment (dev/staging/prod)"
  - type: textarea
    attributes:
      label: "Logs or error messages"
