name: "Feature Request"
description: "Propose a new feature or improvement."
title: "[Feature]: "
labels: ["enhancement", "governance-review"]
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description: "What problem does this solve for trades customers?"
  - type: textarea
    attributes:
      label: "Alignment check"
      description: "Which company value or principle does this serve? (Reliability, Craftsmanship, Stewardship, Builders-First)"
